include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DateLyricsPrefs

DateLyricsPrefs_FILES = DateLyricsRootListController.m
DateLyricsPrefs_FRAMEWORKS = UIKit
DateLyricsPrefs_PRIVATE_FRAMEWORKS = Preferences
DateLyricsPrefs_INSTALL_PATH = /Library/PreferenceBundles
DateLyricsPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
